#Product
components:
  requestBodies:
    nuevoProducto:
      type: object
      properties:
        _id:
          type: ObjectId
          description: id de producto autogenerado por mongo
        name:
          type: string
          description: nombre del producto
        description:
          type: string
          description: breve descripcion del producto
        code:
          type: string
          description: codigo unico de articulo
        thumbnail:
          type: string
          description: link a imagen de articulo
        price:
          type: number
          description: precio del articulor
        stock: 
          type: number
          description: cantidad disponible
        quantity:
          type: number
          description: cantidad seleccionada
      example:
        _id: ObjectId('639a7e4d5048ac793c331d15')
        name: Lapiz Dibujo
        description: Lapiz HB
        code: 136
        thumbnail: https://cdn0.iconfinder.com/data/icons/shift-free/32/Pencil-512.png
        price: 55.56
        stock: 100
        quantity: 100
  schemas:
    Product:
      type: object
      properties:
        id:
          type: ObjectId
          description: Id de producto autogenerada por la base de datos mongo
        name:
          type: string
        description:
          type: string
        code:
          type: string
        thumbnail:
          type: string
        price:
          type: number
        stock: 
          type: number
        quantity:
          type: number
      example:
        id: 639a5882eeaf14b182f624c4
        name: Calculadora Cientifica
        description: saraza
        code: 135
        thumbnail: https://cdn3.iconfinder.com/data/icons/education-209/64/calculator-math-tool-school-256.png
        price: 455.56
        stock: 100       
        quantity: 100
paths:
  /api/products/ :
    get:
      summary: Obtiene la lista completa de productos
      tags:
        - Productos
      responses:
        "200":
          description: Los productos se obtuvieron correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /api/products/639a5882eeaf14b182f624c4:
    get:
      summary: Obtiene un producto por su id
      tags:
        - Productos
      responses:
        "200":
          description: El producto se obtuvo correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Agrega un producto por su id
      tags:
        - Productos
      responses:
        "200":
          description: El producto se obtuvo correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    update:
      summary: Actualiza un producto por su id
      tags:
        - Productos
      responses:
        "200":
          description: El producto se actualizo correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    delete:
      summary: Borra un producto segun su id
      tags:
        - Productos
      responses:
        "200":
          description: El producto se borro correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'        


